{
    "name":"Customer Product Code On Customer Master",
    "version":"1.0",
    "summary": "Custom Customer Product Code fields in sale and Invoice",
    "author": "Odoo PSIN",
    "website": "https://www.odoo.com",
    "odoo_task_id": "4098713",
    "depends":[
        "base_automation",
        "contacts",
        "sale_management",
        "account_accountant",
        "stock"
        ],
    "data":[
        'models/customer_product_code_details_model.xml',
        'security/ir.model.access.csv',
        'data/customer_product_code_details_fields.xml',
        'data/res_partner_fields.xml',
        'data/account_move_line_fields.xml',
        'data/sale_order_line_fields.xml',
        'data/stock_move_fields.xml',
        'data/server_actions.xml',
        'data/base_automation.xml',
        'views/sale_order_line_views.xml',
        'views/account_move_line_views.xml',
        'views/customer_product_code_details_views.xml',
        'views/res_partner_views.xml',
        'views/stock_picking_views.xml',
    ],
    "license":"LGPL-3",
    "installble":True,
    "auto_install": False,
    "application": False,
}
